from django.db import models
from django_extensions.db.fields import AutoSlugField, ShortUUIDField,CreationDateTimeField




class Product(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200)
    description = models.CharField(max_length=499, blank=True, null=True)
    price = models.JSONField()
    image = models.ImageField(upload_to='product_image', blank=True, null=True)
    category = models.CharField(blank=True, null=True)
    rating = models.JSONField()
    slug = AutoSlugField(populate_from='title')

    def __str__(self) -> str:
        return f"{self.title}  ({self.slug})"
    



class OrderItem(models.Model):
    id = models.CharField(max_length=200, primary_key=True) # GENERATED BY FRONTEND
    quantity = models.IntegerField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='product')

    def __str__(self) -> str:
        return self.id




class Transaction(models.Model):
    id = ShortUUIDField(primary_key=True)
    orders = models.ManyToManyField(OrderItem)
    successful = models.BooleanField(default=False)
    created = CreationDateTimeField(null=True)
    